import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const colleges = [
  {
    name: "Christ's College",
    founded: 1505,
    address: "St Andrew's Street, Cambridge CB2 3BU",
    description: "Founded by Lady Margaret Beaufort, mother of King Henry VII. Known for its beautiful First Court and the famous 'Christ's Pieces' nearby.",
    website: "https://www.christs.cam.ac.uk",
    latitude: 52.2044,
    longitude: 0.1244,
    motto: "Souvent me Souvient (Often I Remember)",
  },
  {
    name: "Churchill College",
    founded: 1960,
    address: "Storey's Way, Cambridge CB3 0DS",
    description: "Founded as a national and Commonwealth memorial to Sir Winston Churchill. Known for its modernist architecture and strong focus on science and technology.",
    website: "https://www.chu.cam.ac.uk",
    latitude: 52.2124,
    longitude: 0.1034,
    motto: "Forward",
  },
  {
    name: "Clare College",
    founded: 1326,
    address: "Trinity Lane, Cambridge CB2 1TL",
    description: "The second oldest college in Cambridge. Famous for its beautiful gardens and the oldest bridge over the River Cam.",
    website: "https://www.clare.cam.ac.uk",
    latitude: 52.2054,
    longitude: 0.1154,
    motto: "Mens Gratissima (A Most Grateful Mind)",
  },
  {
    name: "Clare Hall",
    founded: 1965,
    address: "Herschel Road, Cambridge CB3 9AL",
    description: "A graduate college known for its international community and modern architecture.",
    website: "https://www.clarehall.cam.ac.uk",
    latitude: 52.2104,
    longitude: 0.1094,
    motto: "Honor et Fides (Honour and Faith)",
  },
  {
    name: "Corpus Christi College",
    founded: 1352,
    address: "Trumpington Street, Cambridge CB2 1RH",
    description: "Known for its unique clock, the Corpus Clock, and its medieval Old Court. The only college to be founded by the townspeople of Cambridge.",
    website: "https://www.corpus.cam.ac.uk",
    latitude: 52.2024,
    longitude: 0.1174,
    motto: "Floreat Antiqua Domus (May the Ancient House Flourish)",
  },
  {
    name: "Darwin College",
    founded: 1964,
    address: "Silver Street, Cambridge CB3 9EU",
    description: "The first graduate-only college in Cambridge. Named after the Darwin family, who lived in the college's main building.",
    website: "https://www.darwin.cam.ac.uk",
    latitude: 52.2034,
    longitude: 0.1144,
    motto: "Non Ut Solum (Not For Oneself Alone)",
  },
  {
    name: "Downing College",
    founded: 1800,
    address: "Regent Street, Cambridge CB2 1DQ",
    description: "Known for its neoclassical architecture and spacious grounds. The only college to be built in the 19th century.",
    website: "https://www.dow.cam.ac.uk",
    latitude: 52.2004,
    longitude: 0.1244,
    motto: "Quaerere Verum (Seek the Truth)",
  },
  {
    name: "Emmanuel College",
    founded: 1584,
    address: "St Andrew's Street, Cambridge CB2 3AP",
    description: "Known for its beautiful gardens and the famous 'Emmanuel ducks'. Has a strong tradition in the sciences.",
    website: "https://www.emma.cam.ac.uk",
    latitude: 52.2044,
    longitude: 0.1214,
    motto: "Deo et Patriae (For God and Country)",
  },
  {
    name: "Fitzwilliam College",
    founded: 1869,
    address: "Storey's Way, Cambridge CB3 0DG",
    description: "Originally founded as a non-collegiate institution. Known for its modern architecture and strong academic performance.",
    website: "https://www.fitz.cam.ac.uk",
    latitude: 52.2114,
    longitude: 0.1044,
    motto: "Ex Antiquis Et Novissimis Optima (The Best of the Old and the New)",
  },
  {
    name: "Girton College",
    founded: 1869,
    address: "Huntingdon Road, Cambridge CB3 0JG",
    description: "The first women's college in Cambridge. Known for its distance from the city center and its beautiful gardens.",
    website: "https://www.girton.cam.ac.uk",
    latitude: 52.2284,
    longitude: 0.0844,
    motto: "Better is Wisdom than Weapons of War",
  },
  {
    name: "Gonville & Caius College",
    founded: 1348,
    address: "Trinity Street, Cambridge CB2 1TA",
    description: "Known for its three gates representing the stages of a student's life. Has produced more Nobel Prize winners than any other college.",
    website: "https://www.cai.cam.ac.uk",
    latitude: 52.2054,
    longitude: 0.1164,
    motto: "Where the Spirit is Free",
  },
  {
    name: "Homerton College",
    founded: 1768,
    address: "Hills Road, Cambridge CB2 8PH",
    description: "Originally a teacher training college, now a full college of the university. Known for its Victorian architecture.",
    website: "https://www.homerton.cam.ac.uk",
    latitude: 52.1844,
    longitude: 0.1244,
    motto: "Respice Finem (Look to the End)",
  },
  {
    name: "Hughes Hall",
    founded: 1885,
    address: "Mortimer Road, Cambridge CB1 2EW",
    description: "The oldest graduate college in Cambridge. Known for its international community and strong focus on education.",
    website: "https://www.hughes.cam.ac.uk",
    latitude: 52.2004,
    longitude: 0.1244,
    motto: "Disce Aut Discede (Learn or Depart)",
  },
  {
    name: "Jesus College",
    founded: 1496,
    address: "Jesus Lane, Cambridge CB5 8BL",
    description: "Known for its beautiful chapel and extensive grounds. The college buildings were originally part of a nunnery.",
    website: "https://www.jesus.cam.ac.uk",
    latitude: 52.2084,
    longitude: 0.1244,
    motto: "Rex Iesus (Jesus is King)",
  },
  {
    name: "King's College",
    founded: 1441,
    address: "King's Parade, Cambridge CB2 1ST",
    description: "Famous for its chapel, choir, and the annual Christmas Eve service broadcast worldwide. One of the most iconic colleges in Cambridge.",
    website: "https://www.kings.cam.ac.uk",
    latitude: 52.2044,
    longitude: 0.1144,
    motto: "Veritas et Utilitas (Truth and Usefulness)",
  },
  {
    name: "Lucy Cavendish College",
    founded: 1965,
    address: "Lady Margaret Road, Cambridge CB3 0BU",
    description: "A women's college known for its focus on mature students and its supportive community.",
    website: "https://www.lucy-cav.cam.ac.uk",
    latitude: 52.2114,
    longitude: 0.1044,
    motto: "Libertas Per Veritatem (Freedom Through Truth)",
  },
  {
    name: "Magdalene College",
    founded: 1428,
    address: "Magdalene Street, Cambridge CB3 0AG",
    description: "Known for its beautiful riverside location and the Pepys Library. The only college to pronounce its name 'Maudlyn'.",
    website: "https://www.magd.cam.ac.uk",
    latitude: 52.2094,
    longitude: 0.1174,
    motto: "Garde Ta Foy (Keep Your Faith)",
  },
  {
    name: "Murray Edwards College",
    founded: 1954,
    address: "Huntingdon Road, Cambridge CB3 0DF",
    description: "A women's college known for its modern architecture and the Women's Art Collection. Formerly known as New Hall.",
    website: "https://www.murrayedwards.cam.ac.uk",
    latitude: 52.2134,
    longitude: 0.1044,
    motto: "Through Wisdom to Freedom",
  },
  {
    name: "Newnham College",
    founded: 1871,
    address: "Sidgwick Avenue, Cambridge CB3 9DF",
    description: "One of the first women's colleges in Cambridge. Known for its beautiful gardens and the famous 'Newnham Grind'.",
    website: "https://www.newn.cam.ac.uk",
    latitude: 52.2014,
    longitude: 0.1074,
    motto: "Non Ministrari sed Ministrare (Not to be Served but to Serve)",
  },
  {
    name: "Pembroke College",
    founded: 1347,
    address: "Trumpington Street, Cambridge CB2 1RF",
    description: "The third oldest college in Cambridge. Known for its chapel designed by Christopher Wren and its beautiful gardens.",
    website: "https://www.pem.cam.ac.uk",
    latitude: 52.2024,
    longitude: 0.1174,
    motto: "Illustre et Venerabile (Illustrious and Venerable)",
  },
  {
    name: "Peterhouse",
    founded: 1284,
    address: "Trumpington Street, Cambridge CB2 1RD",
    description: "The oldest college in Cambridge. Known for its small size and strong academic tradition.",
    website: "https://www.pet.cam.ac.uk",
    latitude: 52.2024,
    longitude: 0.1174,
    motto: "Floreat Domus (May the House Flourish)",
  },
  {
    name: "Queens' College",
    founded: 1448,
    address: "Silver Street, Cambridge CB3 9ET",
    description: "Known for its Mathematical Bridge and beautiful riverside location. The college's name refers to two queens: Margaret of Anjou and Elizabeth Woodville.",
    website: "https://www.queens.cam.ac.uk",
    latitude: 52.2034,
    longitude: 0.1144,
    motto: "Floreat Domus (May the House Flourish)",
  },
  {
    name: "Robinson College",
    founded: 1979,
    address: "Grange Road, Cambridge CB3 9AN",
    description: "The newest college in Cambridge. Known for its modern architecture and beautiful gardens.",
    website: "https://www.robinson.cam.ac.uk",
    latitude: 52.2074,
    longitude: 0.1044,
    motto: "Awareness, Thought, Excellence",
  },
  {
    name: "Selwyn College",
    founded: 1882,
    address: "Grange Road, Cambridge CB3 9DQ",
    description: "Named after George Augustus Selwyn, the first Bishop of New Zealand. Known for its friendly atmosphere and strong academic performance.",
    website: "https://www.sel.cam.ac.uk",
    latitude: 52.2074,
    longitude: 0.1044,
    motto: "In Fide Vade (Go Forward in Faith)",
  },
  {
    name: "Sidney Sussex College",
    founded: 1596,
    address: "Sidney Street, Cambridge CB2 3HU",
    description: "Known for its chapel and the famous 'Sidney Sussex Brain'. The college's full name is 'The College of the Lady Frances Sidney Sussex'.",
    website: "https://www.sid.cam.ac.uk",
    latitude: 52.2044,
    longitude: 0.1214,
    motto: "Deo et Patriae (For God and Country)",
  },
  {
    name: "St Catharine's College",
    founded: 1473,
    address: "Trumpington Street, Cambridge CB2 1RL",
    description: "Known as 'Catz' to its students. Famous for its central location and the 'Catz Run'.",
    website: "https://www.caths.cam.ac.uk",
    latitude: 52.2024,
    longitude: 0.1174,
    motto: "Nova et Vetera (The New and the Old)",
  },
  {
    name: "St Edmund's College",
    founded: 1896,
    address: "Mount Pleasant, Cambridge CB3 0BN",
    description: "A graduate college known for its international community and strong focus on research.",
    website: "https://www.st-edmunds.cam.ac.uk",
    latitude: 52.2114,
    longitude: 0.1044,
    motto: "Per Re et Verba (Through Deeds and Words)",
  },
  {
    name: "St John's College",
    founded: 1511,
    address: "St John's Street, Cambridge CB2 1TP",
    description: "Known for its beautiful architecture, including the famous Bridge of Sighs. One of the largest and wealthiest colleges.",
    website: "https://www.joh.cam.ac.uk",
    latitude: 52.2084,
    longitude: 0.1154,
    motto: "Souvent me Souvient (Often I Remember)",
  },
  {
    name: "Trinity College",
    founded: 1546,
    address: "Trinity Street, Cambridge CB2 1TQ",
    description: "The largest college in Cambridge. Known for its Great Court, the largest enclosed court in Cambridge, and its impressive alumni.",
    website: "https://www.trin.cam.ac.uk",
    latitude: 52.2064,
    longitude: 0.1164,
    motto: "Virtus Vera Nobilitas (Virtue is True Nobility)",
  },
  {
    name: "Trinity Hall",
    founded: 1350,
    address: "Trinity Lane, Cambridge CB2 1TJ",
    description: "Known as 'Tit Hall' to distinguish it from Trinity College. Famous for its beautiful riverside location and strong tradition in law.",
    website: "https://www.trinhall.cam.ac.uk",
    latitude: 52.2054,
    longitude: 0.1154,
    motto: "Floreat Aula (May the Hall Flourish)",
  },
  {
    name: "Wolfson College",
    founded: 1965,
    address: "Barton Road, Cambridge CB3 9BB",
    description: "A graduate college known for its modern architecture and international community. The only college to be named after a living person (Sir Isaac Wolfson).",
    website: "https://www.wolfson.cam.ac.uk",
    latitude: 52.2104,
    longitude: 0.1094,
    motto: "Ring True",
  },
]

async function main() {
  console.log('Start seeding...')
  
  for (const college of colleges) {
    const result = await prisma.college.upsert({
      where: { name: college.name },
      update: {},
      create: college,
    })
    console.log(`Created college: ${result.name}`)
  }
  
  console.log('Seeding finished.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  }) 